// Database types - re-export Prisma generated types
export type {
  Analysis,
  UserFeature,
  Competitor,
  CompetitorFeature,
  ComparisonParameter,
  FeatureMatrixScore,
  GapAnalysisItem,
  BlueOceanInsight,
  Persona,
  PersonaChatMessage,
  PositioningData,
  SimulatedReview,
  AnalysisStatus,
  CompetitorType,
  MVPPriority,
  EntityType,
  GapType,
  GapSeverity,
  OpportunityLevel,
  DifficultyLevel,
  PersonaType,
  MessageRole,
  ReviewSentiment,
} from '@prisma/client';
